export type Dish = {
  _id: string;
  name: string;
  slug: string;
  description: string;
  image: string;
  category: { _id: string; name: string };
  type: "normal" | "vegetarian" | "diet";
  calories: number;
  protein: number;
  fat: number;
  carbohydrates: number;
  cookingTime: number;
  servings: number;
  difficulty: "easy" | "medium" | "hard";
  tags: string[];
  isActive: boolean;
  viewCount: number;
  favoriteCount: number;
  createdAt: string;
  seo: { metaTitle: string; metaDescription: string; canonicalUrl: string };
};

export const MOCK_CATEGORIES = [
  { _id: "cat1", name: "Súp & Bún" },
  { _id: "cat2", name: "Cơm" },
  { _id: "cat3", name: "Khai vị" },
  { _id: "cat4", name: "Bánh mì" },
  { _id: "cat5", name: "Tráng miệng" },
  { _id: "cat6", name: "Canh" },
  { _id: "cat7", name: "Món chính" },
];

export const MOCK_DISHES: Dish[] = [
  {
    _id: "dish1",
    name: "Phở bò tái chín",
    slug: "pho-bo-tai-chin",
    description: "Phở bò truyền thống với nước dùng đậm đà từ xương bò hầm 8 tiếng, thịt tái và chín.",
    image: "",
    category: { _id: "cat1", name: "Súp & Bún" },
    type: "normal",
    calories: 450,
    protein: 32,
    fat: 12,
    carbohydrates: 55,
    cookingTime: 240,
    servings: 4,
    difficulty: "hard",
    tags: ["phở", "bò", "nước dùng", "truyền thống"],
    isActive: true,
    viewCount: 4820,
    favoriteCount: 312,
    createdAt: "2026-06-01",
    seo: { metaTitle: "", metaDescription: "", canonicalUrl: "" },
  },
  {
    _id: "dish2",
    name: "Bún bò Huế",
    slug: "bun-bo-hue",
    description: "Bún bò Huế đặc trưng với nước dùng cay nồng, thơm sả và mắm ruốc.",
    image: "",
    category: { _id: "cat1", name: "Súp & Bún" },
    type: "normal",
    calories: 520,
    protein: 35,
    fat: 18,
    carbohydrates: 60,
    cookingTime: 180,
    servings: 4,
    difficulty: "medium",
    tags: ["bún bò", "Huế", "cay", "sả"],
    isActive: true,
    viewCount: 3610,
    favoriteCount: 245,
    createdAt: "2026-06-02",
    seo: { metaTitle: "", metaDescription: "", canonicalUrl: "" },
  },
  {
    _id: "dish3",
    name: "Cơm tấm sườn nướng",
    slug: "com-tam-suon-nuong",
    description: "Cơm tấm sườn heo nướng thơm ngon kèm bì, chả và nước mắm pha.",
    image: "",
    category: { _id: "cat2", name: "Cơm" },
    type: "normal",
    calories: 680,
    protein: 40,
    fat: 22,
    carbohydrates: 75,
    cookingTime: 60,
    servings: 2,
    difficulty: "medium",
    tags: ["cơm tấm", "sườn", "nướng"],
    isActive: true,
    viewCount: 3120,
    favoriteCount: 198,
    createdAt: "2026-06-03",
    seo: { metaTitle: "", metaDescription: "", canonicalUrl: "" },
  },
  {
    _id: "dish4",
    name: "Bánh mì pate thịt",
    slug: "banh-mi-pate-thit",
    description: "Bánh mì giòn nhân pate gan, thịt nguội, rau cải và tương ớt.",
    image: "",
    category: { _id: "cat4", name: "Bánh mì" },
    type: "normal",
    calories: 380,
    protein: 18,
    fat: 14,
    carbohydrates: 45,
    cookingTime: 20,
    servings: 1,
    difficulty: "easy",
    tags: ["bánh mì", "pate", "thịt nguội"],
    isActive: true,
    viewCount: 2740,
    favoriteCount: 174,
    createdAt: "2026-06-04",
    seo: { metaTitle: "", metaDescription: "", canonicalUrl: "" },
  },
  {
    _id: "dish5",
    name: "Gỏi cuốn tôm thịt",
    slug: "goi-cuon-tom-thit",
    description: "Gỏi cuốn tươi với tôm, thịt heo, bún, rau thơm và tương hoisin.",
    image: "",
    category: { _id: "cat3", name: "Khai vị" },
    type: "normal",
    calories: 180,
    protein: 14,
    fat: 4,
    carbohydrates: 22,
    cookingTime: 30,
    servings: 4,
    difficulty: "easy",
    tags: ["gỏi cuốn", "tôm", "fresh roll"],
    isActive: true,
    viewCount: 2280,
    favoriteCount: 156,
    createdAt: "2026-06-05",
    seo: { metaTitle: "", metaDescription: "", canonicalUrl: "" },
  },
  {
    _id: "dish6",
    name: "Bún chả Hà Nội",
    slug: "bun-cha-ha-noi",
    description: "Bún chả đặc sản Hà Nội với chả viên và chả miếng nướng than hoa.",
    image: "",
    category: { _id: "cat1", name: "Súp & Bún" },
    type: "normal",
    calories: 510,
    protein: 30,
    fat: 20,
    carbohydrates: 52,
    cookingTime: 45,
    servings: 2,
    difficulty: "medium",
    tags: ["bún chả", "Hà Nội", "nướng than"],
    isActive: true,
    viewCount: 1940,
    favoriteCount: 128,
    createdAt: "2026-06-06",
    seo: { metaTitle: "", metaDescription: "", canonicalUrl: "" },
  },
  {
    _id: "dish7",
    name: "Chả giò",
    slug: "cha-gio",
    description: "Chả giò giòn rụm nhân thịt heo, cua, miến, nấm mèo chiên vàng.",
    image: "",
    category: { _id: "cat3", name: "Khai vị" },
    type: "normal",
    calories: 280,
    protein: 12,
    fat: 16,
    carbohydrates: 24,
    cookingTime: 40,
    servings: 6,
    difficulty: "medium",
    tags: ["chả giò", "chiên", "khai vị"],
    isActive: true,
    viewCount: 1750,
    favoriteCount: 110,
    createdAt: "2026-06-07",
    seo: { metaTitle: "", metaDescription: "", canonicalUrl: "" },
  },
  {
    _id: "dish8",
    name: "Canh chua cá lóc",
    slug: "canh-chua-ca-loc",
    description: "Canh chua miền Nam với cá lóc tươi, cà chua, thơm và rau muống.",
    image: "",
    category: { _id: "cat6", name: "Canh" },
    type: "normal",
    calories: 210,
    protein: 22,
    fat: 6,
    carbohydrates: 18,
    cookingTime: 35,
    servings: 4,
    difficulty: "easy",
    tags: ["canh chua", "cá lóc", "miền Nam"],
    isActive: true,
    viewCount: 1580,
    favoriteCount: 94,
    createdAt: "2026-06-08",
    seo: { metaTitle: "", metaDescription: "", canonicalUrl: "" },
  },
  {
    _id: "dish9",
    name: "Thịt kho trứng",
    slug: "thit-kho-trung",
    description: "Thịt heo ba chỉ kho nước dừa với trứng vịt, nước màu đậm đà.",
    image: "",
    category: { _id: "cat7", name: "Món chính" },
    type: "normal",
    calories: 620,
    protein: 38,
    fat: 40,
    carbohydrates: 15,
    cookingTime: 90,
    servings: 4,
    difficulty: "easy",
    tags: ["thịt kho", "trứng", "nước dừa"],
    isActive: true,
    viewCount: 1430,
    favoriteCount: 87,
    createdAt: "2026-06-09",
    seo: { metaTitle: "", metaDescription: "", canonicalUrl: "" },
  },
  {
    _id: "dish10",
    name: "Bánh xèo",
    slug: "banh-xeo",
    description: "Bánh xèo giòn nhân tôm, thịt, giá đỗ ăn kèm rau sống và nước mắm chua ngọt.",
    image: "",
    category: { _id: "cat4", name: "Bánh mì" },
    type: "normal",
    calories: 340,
    protein: 20,
    fat: 15,
    carbohydrates: 35,
    cookingTime: 50,
    servings: 4,
    difficulty: "hard",
    tags: ["bánh xèo", "tôm", "giá đỗ"],
    isActive: false,
    viewCount: 1210,
    favoriteCount: 72,
    createdAt: "2026-06-10",
    seo: { metaTitle: "", metaDescription: "", canonicalUrl: "" },
  },
  {
    _id: "dish11",
    name: "Rau muống xào tỏi",
    slug: "rau-muong-xao-toi",
    description: "Rau muống xào tỏi phi giòn, đơn giản nhưng đậm đà.",
    image: "",
    category: { _id: "cat7", name: "Món chính" },
    type: "vegetarian",
    calories: 120,
    protein: 4,
    fat: 6,
    carbohydrates: 12,
    cookingTime: 10,
    servings: 2,
    difficulty: "easy",
    tags: ["rau muống", "xào tỏi", "chay"],
    isActive: true,
    viewCount: 980,
    favoriteCount: 54,
    createdAt: "2026-06-11",
    seo: { metaTitle: "", metaDescription: "", canonicalUrl: "" },
  },
  {
    _id: "dish12",
    name: "Đậu hũ sốt cà chua",
    slug: "dau-hu-sot-ca-chua",
    description: "Đậu hũ mềm sốt cà chua ngọt chua, thanh đạm bổ dưỡng.",
    image: "",
    category: { _id: "cat7", name: "Món chính" },
    type: "vegetarian",
    calories: 160,
    protein: 10,
    fat: 8,
    carbohydrates: 14,
    cookingTime: 20,
    servings: 2,
    difficulty: "easy",
    tags: ["đậu hũ", "chay", "sốt cà chua"],
    isActive: true,
    viewCount: 860,
    favoriteCount: 47,
    createdAt: "2026-06-12",
    seo: { metaTitle: "", metaDescription: "", canonicalUrl: "" },
  },
  {
    _id: "dish13",
    name: "Phở chay",
    slug: "pho-chay",
    description: "Phở chay nước dùng từ rau củ, nấm hương, đậu hũ và rau thơm.",
    image: "",
    category: { _id: "cat1", name: "Súp & Bún" },
    type: "vegetarian",
    calories: 320,
    protein: 14,
    fat: 6,
    carbohydrates: 58,
    cookingTime: 60,
    servings: 2,
    difficulty: "medium",
    tags: ["phở chay", "nấm", "đậu hũ"],
    isActive: true,
    viewCount: 740,
    favoriteCount: 38,
    createdAt: "2026-06-11",
    seo: { metaTitle: "", metaDescription: "", canonicalUrl: "" },
  },
  {
    _id: "dish14",
    name: "Cơm gạo lứt",
    slug: "com-gao-lut",
    description: "Cơm gạo lứt nguyên cám ăn kèm muối mè và rau củ hấp.",
    image: "",
    category: { _id: "cat2", name: "Cơm" },
    type: "diet",
    calories: 240,
    protein: 6,
    fat: 2,
    carbohydrates: 50,
    cookingTime: 45,
    servings: 2,
    difficulty: "easy",
    tags: ["gạo lứt", "ăn kiêng", "healthy"],
    isActive: true,
    viewCount: 620,
    favoriteCount: 29,
    createdAt: "2026-06-10",
    seo: { metaTitle: "", metaDescription: "", canonicalUrl: "" },
  },
  {
    _id: "dish15",
    name: "Salad rau củ quinoa",
    slug: "salad-rau-cu-quinoa",
    description: "Salad quinoa với cà chua bi, dưa leo, bơ, ớt chuông và sốt chanh dầu ô liu.",
    image: "",
    category: { _id: "cat3", name: "Khai vị" },
    type: "diet",
    calories: 290,
    protein: 9,
    fat: 14,
    carbohydrates: 32,
    cookingTime: 15,
    servings: 1,
    difficulty: "easy",
    tags: ["salad", "quinoa", "healthy", "ăn kiêng"],
    isActive: false,
    viewCount: 510,
    favoriteCount: 22,
    createdAt: "2026-06-09",
    seo: { metaTitle: "", metaDescription: "", canonicalUrl: "" },
  },
];
