export type Ingredient = {
  _id: string;
  name: string;
  defaultUnit: string;
};

export type RecipeIngredientRow = {
  ingredientId: string;
  amount: number;
  unit: string;
  note: string;
};

export type InstructionRow = {
  step: number;
  description: string;
  image: string;
};

export type Recipe = {
  _id: string;
  dishId: string;
  dishName: string;
  title: string;
  slug: string;
  source: string;
  sourceUrl: string;
  description: string;
  image: string;
  videoUrl: string;
  servings: number;
  cookingTime: number;
  difficulty: "easy" | "medium" | "hard";
  calories: number;
  protein: number;
  fat: number;
  carbohydrates: number;
  ingredients: RecipeIngredientRow[];
  instructions: InstructionRow[];
  isActive: boolean;
  createdAt: string;
};

export const MOCK_INGREDIENTS: Ingredient[] = [
  { _id: "ing1", name: "Thịt bò", defaultUnit: "g" },
  { _id: "ing2", name: "Xương bò", defaultUnit: "g" },
  { _id: "ing3", name: "Bánh phở", defaultUnit: "g" },
  { _id: "ing4", name: "Hành tây", defaultUnit: "cái" },
  { _id: "ing5", name: "Gừng", defaultUnit: "g" },
  { _id: "ing6", name: "Hành lá", defaultUnit: "g" },
  { _id: "ing7", name: "Ngò gai", defaultUnit: "g" },
  { _id: "ing8", name: "Nước mắm", defaultUnit: "tbsp" },
  { _id: "ing9", name: "Muối", defaultUnit: "tsp" },
  { _id: "ing10", name: "Đường", defaultUnit: "tbsp" },
  { _id: "ing11", name: "Thịt heo ba chỉ", defaultUnit: "g" },
  { _id: "ing12", name: "Sả", defaultUnit: "cây" },
  { _id: "ing13", name: "Mắm ruốc", defaultUnit: "tbsp" },
  { _id: "ing14", name: "Bún bò", defaultUnit: "g" },
  { _id: "ing15", name: "Tôm tươi", defaultUnit: "g" },
  { _id: "ing16", name: "Bún tươi", defaultUnit: "g" },
  { _id: "ing17", name: "Rau sống các loại", defaultUnit: "g" },
  { _id: "ing18", name: "Dầu ăn", defaultUnit: "tbsp" },
  { _id: "ing19", name: "Tỏi", defaultUnit: "tép" },
  { _id: "ing20", name: "Cà rốt", defaultUnit: "g" },
  { _id: "ing21", name: "Nấm hương", defaultUnit: "g" },
  { _id: "ing22", name: "Miến", defaultUnit: "g" },
  { _id: "ing23", name: "Trứng vịt", defaultUnit: "quả" },
  { _id: "ing24", name: "Nước dừa", defaultUnit: "ml" },
  { _id: "ing25", name: "Cá lóc", defaultUnit: "g" },
];

export const MOCK_DISHES_SELECT = [
  { _id: "dish1", name: "Phở bò tái chín" },
  { _id: "dish2", name: "Bún bò Huế" },
  { _id: "dish3", name: "Cơm tấm sườn nướng" },
  { _id: "dish4", name: "Bánh mì pate thịt" },
  { _id: "dish5", name: "Gỏi cuốn tôm thịt" },
  { _id: "dish6", name: "Bún chả Hà Nội" },
  { _id: "dish7", name: "Chả giò" },
  { _id: "dish8", name: "Canh chua cá lóc" },
  { _id: "dish9", name: "Thịt kho trứng" },
  { _id: "dish10", name: "Bánh xèo" },
  { _id: "dish11", name: "Rau muống xào tỏi" },
  { _id: "dish12", name: "Đậu hũ sốt cà chua" },
  { _id: "dish13", name: "Phở chay" },
];

export const MOCK_RECIPES: Recipe[] = [
  {
    _id: "rec1",
    dishId: "dish1",
    dishName: "Phở bò tái chín",
    title: "Phở bò truyền thống kiểu Hà Nội",
    slug: "pho-bo-truyen-thong-kieu-ha-noi",
    source: "Bách Hóa XANH",
    sourceUrl: "https://bachhoaxanh.com",
    description: "Công thức phở bò chuẩn vị Hà Nội với nước dùng trong, thơm hoa hồi.",
    image: "",
    videoUrl: "",
    servings: 4,
    cookingTime: 240,
    difficulty: "hard",
    calories: 450,
    protein: 32,
    fat: 12,
    carbohydrates: 55,
    ingredients: [
      { ingredientId: "ing2", amount: 1000, unit: "g", note: "rửa sạch, trần nước sôi" },
      { ingredientId: "ing1", amount: 500, unit: "g", note: "thái lát mỏng" },
      { ingredientId: "ing3", amount: 400, unit: "g", note: "" },
      { ingredientId: "ing4", amount: 2, unit: "cái", note: "nướng thơm" },
      { ingredientId: "ing5", amount: 50, unit: "g", note: "nướng thơm" },
      { ingredientId: "ing8", amount: 3, unit: "tbsp", note: "" },
    ],
    instructions: [
      { step: 1, description: "Trần xương bò qua nước sôi 5 phút, rửa sạch rồi cho vào nồi với 3 lít nước lạnh.", image: "" },
      { step: 2, description: "Nướng hành tây và gừng trực tiếp trên lửa đến khi xém vàng, cạo sạch lớp đen.", image: "" },
      { step: 3, description: "Cho hành tây, gừng nướng vào nồi xương. Thêm hoa hồi, quế, đinh hương rang thơm. Hầm trên lửa nhỏ 3-4 tiếng.", image: "" },
      { step: 4, description: "Nêm nước dùng với nước mắm, muối, đường cho vừa miệng. Vớt bọt thường xuyên.", image: "" },
      { step: 5, description: "Trụng bánh phở qua nước sôi, cho vào tô. Xếp thịt bò tái và chín lên trên, chan nước dùng sôi.", image: "" },
      { step: 6, description: "Ăn kèm giá đỗ, húng quế, chanh, ớt theo khẩu vị.", image: "" },
    ],
    isActive: true,
    createdAt: "2026-06-01",
  },
  {
    _id: "rec2",
    dishId: "dish2",
    dishName: "Bún bò Huế",
    title: "Bún bò Huế chuẩn vị miền Trung",
    slug: "bun-bo-hue-chuan-vi-mien-trung",
    source: "Cookpad",
    sourceUrl: "https://cookpad.com",
    description: "Bún bò Huế đậm đà với nước dùng cay nồng, thơm mắm ruốc và sả.",
    image: "",
    videoUrl: "",
    servings: 4,
    cookingTime: 180,
    difficulty: "medium",
    calories: 520,
    protein: 35,
    fat: 18,
    carbohydrates: 60,
    ingredients: [
      { ingredientId: "ing2", amount: 800, unit: "g", note: "" },
      { ingredientId: "ing11", amount: 500, unit: "g", note: "cắt khoanh" },
      { ingredientId: "ing14", amount: 400, unit: "g", note: "" },
      { ingredientId: "ing12", amount: 4, unit: "cây", note: "đập dập" },
      { ingredientId: "ing13", amount: 2, unit: "tbsp", note: "phi thơm" },
      { ingredientId: "ing8", amount: 2, unit: "tbsp", note: "" },
    ],
    instructions: [
      { step: 1, description: "Hầm xương bò với sả đập dập trong 2 tiếng trên lửa nhỏ. Vớt bọt liên tục.", image: "" },
      { step: 2, description: "Phi mắm ruốc với dầu ăn và sả băm đến khi thơm, cho vào nước dùng.", image: "" },
      { step: 3, description: "Thêm ớt bột, muối, nước mắm vào nước dùng. Nếm lại cho vừa ăn.", image: "" },
      { step: 4, description: "Trụng bún qua nước sôi, cho vào tô. Chan nước dùng sôi, xếp thịt và chả lên trên.", image: "" },
    ],
    isActive: true,
    createdAt: "2026-06-02",
  },
  {
    _id: "rec3",
    dishId: "dish5",
    dishName: "Gỏi cuốn tôm thịt",
    title: "Gỏi cuốn tươi kiểu miền Nam",
    slug: "goi-cuon-tuoi-kieu-mien-nam",
    source: "Cookpad",
    sourceUrl: "https://cookpad.com",
    description: "Gỏi cuốn tươi mát với tôm hồng, thịt heo luộc, rau thơm và bún.",
    image: "",
    videoUrl: "",
    servings: 4,
    cookingTime: 30,
    difficulty: "easy",
    calories: 180,
    protein: 14,
    fat: 4,
    carbohydrates: 22,
    ingredients: [
      { ingredientId: "ing15", amount: 300, unit: "g", note: "luộc chín bóc vỏ" },
      { ingredientId: "ing11", amount: 200, unit: "g", note: "luộc thái lát" },
      { ingredientId: "ing16", amount: 200, unit: "g", note: "" },
      { ingredientId: "ing17", amount: 100, unit: "g", note: "rửa sạch" },
    ],
    instructions: [
      { step: 1, description: "Luộc tôm với chút muối đến khi chín hồng, vớt ra để nguội rồi bóc vỏ, chẻ đôi.", image: "" },
      { step: 2, description: "Luộc thịt heo với hành và muối, để nguội rồi thái lát mỏng.", image: "" },
      { step: 3, description: "Nhúng bánh tráng qua nước ấm cho mềm. Xếp rau, bún, tôm, thịt lên rồi cuốn chặt.", image: "" },
      { step: 4, description: "Pha tương hoisin với tương đen, đậu phộng rang giã nhỏ để chấm.", image: "" },
    ],
    isActive: true,
    createdAt: "2026-06-03",
  },
  {
    _id: "rec4",
    dishId: "dish9",
    dishName: "Thịt kho trứng",
    title: "Thịt kho trứng nước dừa kiểu miền Nam",
    slug: "thit-kho-trung-nuoc-dua-mien-nam",
    source: "Điện Máy Xanh",
    sourceUrl: "https://dienmayxanh.com",
    description: "Thịt ba chỉ kho nước dừa với trứng vịt — đậm đà, béo ngậy.",
    image: "",
    videoUrl: "",
    servings: 4,
    cookingTime: 90,
    difficulty: "easy",
    calories: 620,
    protein: 38,
    fat: 40,
    carbohydrates: 15,
    ingredients: [
      { ingredientId: "ing11", amount: 700, unit: "g", note: "cắt miếng vuông 4cm" },
      { ingredientId: "ing23", amount: 6, unit: "quả", note: "luộc chín bóc vỏ" },
      { ingredientId: "ing24", amount: 400, unit: "ml", note: "dừa tươi" },
      { ingredientId: "ing10", amount: 3, unit: "tbsp", note: "thắng nước màu" },
      { ingredientId: "ing8", amount: 2, unit: "tbsp", note: "" },
    ],
    instructions: [
      { step: 1, description: "Thắng đường với chút nước đến khi chuyển màu cánh gián, cho thịt vào đảo đều.", image: "" },
      { step: 2, description: "Cho nước mắm, tỏi băm vào, xào thêm 2-3 phút cho thịt thấm gia vị.", image: "" },
      { step: 3, description: "Rót nước dừa vào xâm xấp thịt. Đun sôi rồi hạ lửa nhỏ kho 45 phút.", image: "" },
      { step: 4, description: "Cho trứng vịt đã bóc vỏ vào kho thêm 20 phút đến khi nước sánh lại.", image: "" },
    ],
    isActive: true,
    createdAt: "2026-06-04",
  },
  {
    _id: "rec5",
    dishId: "dish8",
    dishName: "Canh chua cá lóc",
    title: "Canh chua cá lóc miền Tây",
    slug: "canh-chua-ca-loc-mien-tay",
    source: "Cookpad",
    sourceUrl: "https://cookpad.com",
    description: "Canh chua đặc trưng miền Tây với cá lóc tươi, me chua và rau bạc hà.",
    image: "",
    videoUrl: "",
    servings: 4,
    cookingTime: 35,
    difficulty: "easy",
    calories: 210,
    protein: 22,
    fat: 6,
    carbohydrates: 18,
    ingredients: [
      { ingredientId: "ing25", amount: 600, unit: "g", note: "cắt khúc, ướp muối" },
      { ingredientId: "ing20", amount: 200, unit: "g", note: "cà chua bổ múi" },
      { ingredientId: "ing8", amount: 2, unit: "tbsp", note: "" },
      { ingredientId: "ing10", amount: 1, unit: "tbsp", note: "" },
    ],
    instructions: [
      { step: 1, description: "Nấu nước me chua với 1 lít nước lọc, lọc lấy nước chua.", image: "" },
      { step: 2, description: "Đun sôi nước me, cho cà chua, thơm vào nấu 5 phút.", image: "" },
      { step: 3, description: "Cho cá lóc vào nấu đến khi chín (khoảng 8-10 phút). Không khuấy mạnh để cá không vỡ.", image: "" },
      { step: 4, description: "Nêm nước mắm, đường, muối cho vừa miệng. Thêm giá đỗ và rau om, tắt bếp.", image: "" },
    ],
    isActive: true,
    createdAt: "2026-06-05",
  },
  {
    _id: "rec6",
    dishId: "dish7",
    dishName: "Chả giò",
    title: "Chả giò nhân hải sản giòn tan",
    slug: "cha-gio-nhan-hai-san-gion-tan",
    source: "YouTube",
    sourceUrl: "https://youtube.com",
    description: "Chả giò giòn rụm, nhân hải sản thơm ngon chiên vàng hoàn hảo.",
    image: "",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    servings: 6,
    cookingTime: 40,
    difficulty: "medium",
    calories: 280,
    protein: 12,
    fat: 16,
    carbohydrates: 24,
    ingredients: [
      { ingredientId: "ing15", amount: 200, unit: "g", note: "băm nhỏ" },
      { ingredientId: "ing11", amount: 200, unit: "g", note: "băm" },
      { ingredientId: "ing22", amount: 50, unit: "g", note: "ngâm nở" },
      { ingredientId: "ing21", amount: 30, unit: "g", note: "ngâm thái nhỏ" },
      { ingredientId: "ing18", amount: 500, unit: "ml", note: "chiên ngập dầu" },
    ],
    instructions: [
      { step: 1, description: "Trộn đều tôm băm, thịt heo, miến, nấm, cà rốt bào sợi với gia vị.", image: "" },
      { step: 2, description: "Trải bánh tráng, cho nhân vào cuốn chặt tay, bọc đầu bánh tráng ướt để dán.", image: "" },
      { step: 3, description: "Đun dầu đến 170°C, thả chả giò vào chiên lửa vừa đến khi vàng đều.", image: "" },
      { step: 4, description: "Vớt ra giấy thấm dầu. Ăn kèm nước chấm chua ngọt và rau sống.", image: "" },
    ],
    isActive: true,
    createdAt: "2026-06-06",
  },
  {
    _id: "rec7",
    dishId: "dish6",
    dishName: "Bún chả Hà Nội",
    title: "Bún chả Hà Nội than hoa truyền thống",
    slug: "bun-cha-ha-noi-than-hoa-truyen-thong",
    source: "VnExpress",
    sourceUrl: "https://vnexpress.net",
    description: "Bún chả nướng than hoa kiểu Hà Nội với chả viên và chả miếng.",
    image: "",
    videoUrl: "",
    servings: 2,
    cookingTime: 45,
    difficulty: "medium",
    calories: 510,
    protein: 30,
    fat: 20,
    carbohydrates: 52,
    ingredients: [
      { ingredientId: "ing11", amount: 500, unit: "g", note: "500g nạc vai + 200g ba chỉ" },
      { ingredientId: "ing16", amount: 300, unit: "g", note: "" },
      { ingredientId: "ing8", amount: 3, unit: "tbsp", note: "" },
      { ingredientId: "ing10", amount: 2, unit: "tbsp", note: "" },
    ],
    instructions: [
      { step: 1, description: "Ướp thịt với nước mắm, đường, hành băm, tỏi, ớt ít nhất 30 phút.", image: "" },
      { step: 2, description: "Viên chả tròn (200g thịt băm), chả miếng dẹt từ thịt ba chỉ.", image: "" },
      { step: 3, description: "Nướng chả trên than hoa đến khi chín đều và có vết cháy xém thơm.", image: "" },
      { step: 4, description: "Pha nước chấm: nước mắm + đường + giấm + tỏi ớt + nước ấm. Cho chả vào bát nước chấm.", image: "" },
    ],
    isActive: true,
    createdAt: "2026-06-07",
  },
  {
    _id: "rec8",
    dishId: "dish13",
    dishName: "Phở chay",
    title: "Phở chay nước dùng rau củ",
    slug: "pho-chay-nuoc-dung-rau-cu",
    source: "Chay Tịnh Tâm",
    sourceUrl: "",
    description: "Phở chay thanh đạm nước dùng từ củ cải, hành tây, nấm hương.",
    image: "",
    videoUrl: "",
    servings: 2,
    cookingTime: 60,
    difficulty: "medium",
    calories: 320,
    protein: 14,
    fat: 6,
    carbohydrates: 58,
    ingredients: [
      { ingredientId: "ing4", amount: 2, unit: "cái", note: "nướng thơm" },
      { ingredientId: "ing5", amount: 30, unit: "g", note: "nướng thơm" },
      { ingredientId: "ing21", amount: 50, unit: "g", note: "ngâm nước ấm" },
      { ingredientId: "ing3", amount: 300, unit: "g", note: "trụng qua nước sôi" },
    ],
    instructions: [
      { step: 1, description: "Nướng hành tây và gừng đến khi xém vàng. Rang hoa hồi, quế khô trên chảo khô.", image: "" },
      { step: 2, description: "Cho vào nồi với 1.5 lít nước, củ cải, nấm hương và các gia vị. Hầm 45 phút.", image: "" },
      { step: 3, description: "Lọc nước dùng qua rây, nêm nước tương, muối, đường cho vừa ăn.", image: "" },
      { step: 4, description: "Trụng bánh phở, xếp đậu hũ chiên và rau thơm vào tô, chan nước dùng sôi.", image: "" },
    ],
    isActive: true,
    createdAt: "2026-06-08",
  },
  {
    _id: "rec9",
    dishId: "dish11",
    dishName: "Rau muống xào tỏi",
    title: "Rau muống xào tỏi phi vàng",
    slug: "rau-muong-xao-toi-phi-vang",
    source: "Cookpad",
    sourceUrl: "https://cookpad.com",
    description: "Rau muống xào tỏi phi thơm giòn — món rau nhanh ngon cơm ngày thường.",
    image: "",
    videoUrl: "",
    servings: 2,
    cookingTime: 10,
    difficulty: "easy",
    calories: 120,
    protein: 4,
    fat: 6,
    carbohydrates: 12,
    ingredients: [
      { ingredientId: "ing17", amount: 400, unit: "g", note: "rau muống nhặt sạch" },
      { ingredientId: "ing19", amount: 5, unit: "tép", note: "băm nhuyễn" },
      { ingredientId: "ing18", amount: 2, unit: "tbsp", note: "" },
      { ingredientId: "ing9", amount: 0.5, unit: "tsp", note: "" },
    ],
    instructions: [
      { step: 1, description: "Phi tỏi băm trong dầu ăn đến khi vàng thơm. Chú ý lửa vừa để tỏi không cháy đắng.", image: "" },
      { step: 2, description: "Cho rau muống đã nhặt vào xào lửa lớn, đảo nhanh tay liên tục.", image: "" },
      { step: 3, description: "Nêm muối và một chút nước mắm. Xào thêm 1-2 phút đến khi rau chín tới, vẫn giữ màu xanh.", image: "" },
    ],
    isActive: true,
    createdAt: "2026-06-09",
  },
  {
    _id: "rec10",
    dishId: "dish3",
    dishName: "Cơm tấm sườn nướng",
    title: "Cơm tấm sườn nướng than hoa đúng điệu",
    slug: "com-tam-suon-nuong-than-hoa-dung-dieu",
    source: "YouTube",
    sourceUrl: "https://youtube.com",
    description: "Công thức sườn nướng than hoa thơm ngon dùng với cơm tấm và đồ chua.",
    image: "",
    videoUrl: "",
    servings: 2,
    cookingTime: 60,
    difficulty: "medium",
    calories: 680,
    protein: 40,
    fat: 22,
    carbohydrates: 75,
    ingredients: [
      { ingredientId: "ing11", amount: 600, unit: "g", note: "sườn non chặt miếng" },
      { ingredientId: "ing8", amount: 3, unit: "tbsp", note: "" },
      { ingredientId: "ing10", amount: 2, unit: "tbsp", note: "" },
      { ingredientId: "ing19", amount: 4, unit: "tép", note: "băm" },
    ],
    instructions: [
      { step: 1, description: "Ướp sườn với nước mắm, đường, tỏi, dầu hào, sả băm ít nhất 2 tiếng.", image: "" },
      { step: 2, description: "Nướng sườn trên than hoa lửa vừa, lật đều và phết nước ướp liên tục.", image: "" },
      { step: 3, description: "Nướng đến khi sườn chín vàng, có vết cháy xém thơm là đạt.", image: "" },
      { step: 4, description: "Dọn với cơm tấm, bì, chả, đồ chua và nước mắm pha.", image: "" },
    ],
    isActive: false,
    createdAt: "2026-06-10",
  },
];
