services:

  # ===== Backend NestJS =====
  backend:
    build: ./backend
    container_name: app-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "4000:4000"
    networks: [app-net]

  # ===== Frontend Next.js =====
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: app-frontend
    restart: unless-stopped
    depends_on: [backend]
    ports:
      - "3000:3000"
    networks: [app-net]

volumes: {}

networks:
  app-net:
    driver: bridge
